import express from 'express';
import authRoutes from './authRoutes.js';
import ticketRoutes from './ticketRoutes.js';
import stadiumRoutes from './stadiumRoutes.js';
import teamRoutes from './teamRoutes.js'; 
import sectionRoutes from './sectionRoutes.js';
import seatRoutes from './seatRoutes.js';
import matchRoutes from './matchRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import discountRoutes from './discountRoutes.js';
import payRoutes from './payRoutes.js';
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/tickets', ticketRoutes);
router.use('/stadiums',stadiumRoutes);
router.use('/teams',teamRoutes);
router.use('/sections',sectionRoutes);
router.use('/seats',seatRoutes);
router.use('/matches',matchRoutes);
router.use('/bookings',bookingRoutes);
router.use('/discounts',discountRoutes);
router.use('/pays',payRoutes);
export default router;